### PR TITLE
(en/zoro) Hianime again changed its domain added proxies for Hianime

### LINKED ISSUE #914: HiAnime Failed to Bypass Cloudflare on v14.53
### Source information

HiAnime 14.53

### Source language

English

### Steps to reproduce

1. Open Aniyomi.
2. Open HiAnime.
3. Shows "Failed to Bypass Cloudflare".

### Expected behavior

This should show animes.

### Actual behavior

It show "Failed to Bypass Cloudflare".

### Which app are you using?

Aniyomi

### App version

0.16.4.3

### Android version

Android 10

### Other details

Im happily watching anime using HiAnime v14.52 when suddenly a new update pop up and I update it, and then it suddenly stop working and when I load it, it only show Failed to Bypass Cloudflare.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [x] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Arkai1**
Checklist:
Close #914 
- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension
- [x] Have made sure all the icons are in png format

### CODE REVIEW

File: src/en/zoro/src/eu/kanade/tachiyomi/animeextension/en/zoro/HiAnime.kt [hunk 1]
```diff
@@ -45,4 +48,28 @@ class HiAnime : ZoroTheme(
             else -> emptyList()
         }
     }
+    // Added the setupPreferenceScreen method here
+    override fun setupPreferenceScreen(screen: PreferenceScreen) {
+        screen.addPreference(ListPreference(screen.context).apply {
```
Comment (krysanify) [inline src/en/zoro/src/eu/kanade/tachiyomi/animeextension/en/zoro/HiAnime.kt]: need to call `super.setupPreferenceScreen(screen)` as well, otherwise other prefs (quality, hoster, etc) will be overridden.

File: src/en/zoro/src/eu/kanade/tachiyomi/animeextension/en/zoro/HiAnime.kt [hunk 2]
```diff
@@ -37,12 +44,51 @@ class HiAnime : ZoroTheme(
...
+
+    // Added the setupPreferenceScreen method here
+    override fun setupPreferenceScreen(screen: PreferenceScreen) {
+        super.setupPreferenceScreen(screen)
+        screen.addPreference(
+            ListPreference(screen.context).apply {
+                key = PREF_DOMAIN_KEY
+                title = "Preferred domain"
+                entries = arrayOf("hianimez.to", "hianime.to", "hianime.bz", "hianime.pe")
+                entryValues = arrayOf("https://hianimez.to", "https://hianime.to", "https://hianime.bz", "https://hianime.pe")
```
Comment (krysanify) [inline src/en/zoro/src/eu/kanade/tachiyomi/animeextension/en/zoro/HiAnime.kt:71]: .bz appears to be reported as a phishing site also when I opened on browser, may want to remove it.

Comment (Arkai1) [reply src/en/zoro/src/eu/kanade/tachiyomi/animeextension/en/zoro/HiAnime.kt:71]: .bz is their one of official proxies available on .tv as it is says but I don't think that will be issue
