### PR TITLE
AnimePahe: Reverse episode order

### LINKED ISSUE #921: Wrong order of episodes
### Source information

AnimePahe 14.30

### Source language

English

### Steps to reproduce

1. Browse any anime from the AnimePahe extension
2. Notice the episodes are in reversed order

### Expected behavior

First episode should be at bottom, last should be at top

### Actual behavior

First episode is at top, last at bottom, thus aniyomi displays that intermediary episodes are missing

### Which app are you using?

Aniyomi

### App version

preview r8065

### Android version

Android 13

### Other details

No android, aniyomi or extension update has been done between the time where it worked fine and now

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [x] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by kana-shii**
Closes #921 
Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension
- [ ] Have made sure all the icons are in png format

### CODE REVIEW

File: src/en/animepahe/src/eu/kanade/tachiyomi/animeextension/en/animepahe/AnimePahe.kt [hunk 1]
```diff
@@ -162,6 +162,7 @@ class AnimePahe : ConfigurableAnimeSource, AnimeHttpSource() {
                 episode.name = "Episode ${index + 1}"
                 episode
             }
+            .reversed()
```
Comment (krysanify) [inline src/en/animepahe/src/eu/kanade/tachiyomi/animeextension/en/animepahe/AnimePahe.kt:165]: why not just remove the parameter `&sort=episode_desc` at line 150 on `episodeListRequest`?
